<a href="https://colab.research.google.com/github/RaunakRaj2081/python_Language/blob/main/3_3_Working_with_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Creating a Matrix using numpy

In [4]:
m1 = np.array([[3,4],[4,5],[7,8]])
print(m1)

[[3 4]
 [4 5]
 [7 8]]


In [5]:
m1.shape

(3, 2)

#Creating Matrices with Random Values

In [6]:
m = np.random.rand(4,5)
print(m)

[[0.61449013 0.341386   0.07528017 0.23388039 0.58873809]
 [0.63257944 0.4152803  0.68465796 0.47035908 0.45035869]
 [0.89937648 0.62882215 0.66788526 0.99361719 0.92025429]
 [0.25944167 0.7143445  0.44403039 0.17480181 0.37105981]]


In [15]:
# creating matrix with random integers
n = np.random.randint(20,100 , size= (5,6))
print(n)

[[23 81 22 45 98 53]
 [28 87 66 38 70 82]
 [35 31 67 35 81 30]
 [56 81 39 30 36 43]
 [69 54 75 20 39 51]]


#Matrix with all the values as 1

In [19]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


#Null Matrix or Zero Matrix

In [22]:
null_matrix = np.zeros((4,4) , dtype = int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#Identity Matrix

In [23]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
identity_matrix1 = np.eye(3,3 , dtype = int)
print(identity_matrix1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#Transpose of a Matrix

In [25]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[99 93 35 43 16]
 [94 69 84 94 99]
 [36 91  8 79 83]
 [40 66 48 38 61]]


In [26]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[99 94 36 40]
 [93 69 91 66]
 [35 84  8 48]
 [43 94 79 38]
 [16 99 83 61]]
