<a href="https://colab.research.google.com/github/RaunakRaj2081/python_Language/blob/main/3_4_Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Matrix Addition

Two Matrices can be added only if they have the same shape

In [3]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

print(A)
print(B)
A.shape
B.shape

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


(2, 2)

In [4]:
sum = A + B
print(sum)

[[ 8 10]
 [12 14]]


In [7]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))
print(matrix_1)
print(matrix_2)

[[3 1 0]
 [9 5 3]
 [9 7 7]]
[[ 8 17  9]
 [13 10 17]
 [14 14 15]]


In [8]:
sum = np.add(matrix_1, matrix_2)
print(sum)

[[11 18  9]
 [22 15 20]
 [23 21 22]]


#Matrix Subtraction

In [9]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))
print(matrix_1)
print(matrix_2)

[[2 1 0]
 [3 6 7]
 [2 1 6]]
[[19  1  5]
 [ 8  8 15]
 [ 4  3 13]]


In [10]:
diff = np.subtract(matrix_1 , matrix_2)
print(diff)

[[-17   0  -5]
 [ -5  -2  -8]
 [ -2  -2  -7]]


In [11]:
d = matrix_1 - matrix_2
print(d)

[[-17   0  -5]
 [ -5  -2  -8]
 [ -2  -2  -7]]


#Multiplying a matrix by a scalar

In [12]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[2 6 4 7]
 [1 4 1 3]
 [3 1 9 8]
 [1 8 2 8]]


In [13]:
product = np.multiply(x,y)
print(product)

[[10 30 20 35]
 [ 5 20  5 15]
 [15  5 45 40]
 [ 5 40 10 40]]


#Multiplying 2 Matrices

In [14]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))
print(matrix_3)
print(matrix_4)

[[4 3 1]
 [4 3 4]
 [1 4 2]]
[[2 2 2 1]
 [2 1 2 1]
 [1 0 2 0]]


In [15]:
product = np.dot(matrix_3, matrix_4)
print(product)

[[15 11 16  7]
 [18 11 22  7]
 [12  6 14  5]]


In [16]:
product.shape

(3, 4)

#Element wise Matrix Multiplication

In [17]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))
print(matrix_3)
print(matrix_4)

[[4 3 2]
 [4 4 3]
 [1 1 2]]
[[2 2 0]
 [1 1 4]
 [0 1 0]]


In [18]:
product = np.multiply(matrix_3, matrix_4)
print(product)

[[ 8  6  0]
 [ 4  4 12]
 [ 0  1  0]]
