<a href="https://colab.research.google.com/github/RaunakRaj2081/python_Language/blob/main/8_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy - Numerical Python



🧠 What is NumPy?

NumPy (Numerical Python) is a Python library used to do mathematical and logical operations on large amounts of data quickly and easily. It mainly works with arrays (like lists but faster and more powerful).

✅ Why Use NumPy?

1. Faster than Python lists.

2. Requires less memory.

3. Supports multidimensional arrays.

4. Comes with many built-in functions (mean, sum, reshape, etc.).

5. Useful for data science, machine learning, and scientific computing.



In [3]:
import numpy as np

#List vs Numpy time taken

In [ ]:
from time import process_time

time taken by a list

In [ ]:
python_list = [i for i in range(1000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0001431010000008115


time taken by numpy list

In [ ]:
np_array = np.array([i for i in range(1000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.0015161409999997488


#Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating 1 dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

here the 4 represents the no. of columns

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

here 2 represents the no. of rows and
4 represents the no. of columns

here in numpy the value are space separated not comma separated

In [ ]:
# float values
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#initial placeholders in numpy array

In [ ]:
# creating a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# creating a numpy array of ones
y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# creating a numpy array with a particular value
z = np.full((5,4),6)
print(z)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
# creating an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
a = np.random.random((4,5)) # this will give random values between 0 and 1
print(a)

[[0.99632419 0.36501217 0.91838356 0.78547099 0.32300173]
 [0.55939548 0.64877738 0.32138328 0.17831742 0.46994717]
 [0.21083752 0.29439829 0.12049394 0.967558   0.74505876]
 [0.50471031 0.03488262 0.59430222 0.38954415 0.83275786]]


In [ ]:
# numpy array with random integer values within a given range
a = np.random.randint(10,100,(3,5))
print(a)

[[15 23 31 74 90]
 [11 96 84 22 91]
 [86 72 13 60 18]]


In [ ]:
# array of evenly spaced values (a,b,c) -> a,b represents range and c represents number of values
b = np.linspace(10,40,5,dtype=int) # by default float
print(b)

[10 17 25 32 40]


In [ ]:
# array of evenly spaced values (a,b,c) -> a,b represents the range and c represents the step
c = np.arange(10,40,5)
print(c)

[10 15 20 25 30 35]


In [ ]:
# convert a list to numpy array
list = [2,3,4,6,7]
np_array = np.asarray(list)
print(np_array)
type(np_array)

[2 3 4 6 7]


numpy.ndarray

#analysing a numpy array

In [ ]:
d = np.random.randint(20 ,100 , (4,5))
print(d)

[[81 29 46 51 50]
 [67 21 70 78 51]
 [43 94 52 63 25]
 [26 68 27 77 24]]


In [ ]:
# array dimension
print(d.shape)

(4, 5)


In [ ]:
# number of dimensions
print(d.ndim)

2


In [ ]:
# number of elements in an array
print(d.size)

20


In [ ]:
# type of elements in the array
print(d.dtype)

int64


#Mathematical operations on numpy array

In [5]:
ab = np.array([1, 2, 3, 4])

print(np.sum(ab))        # 10
print(np.mean(ab))       # 2.5
print(np.min(ab))        # 1
print(np.max(ab))        # 4
print(np.std(ab))        # Standard Deviation
print(np.sqrt(ab))

10
2.5
1
4
1.118033988749895
[1.         1.41421356 1.73205081 2.        ]


In [ ]:
# first understand what list does
a = [2,5,7,3]
b = [2,9,8,1]
print(a+b)  # here it joins both the arrays

[2, 5, 7, 3, 2, 9, 8, 1]


In [ ]:
# in numpy
c = np.random.randint(10,20,(3,4))
d = np.random.randint(30,50,(3,4))
print(c)
print(d)

[[18 18 10 18]
 [16 18 13 16]
 [16 18 13 12]]
[[43 46 35 47]
 [31 47 30 38]
 [47 42 47 32]]


In [ ]:
# operations
print(c+d)
print(c-d)
print(c*d)
print(c/d)

[[61 64 45 65]
 [47 65 43 54]
 [63 60 60 44]]
[[-25 -28 -25 -29]
 [-15 -29 -17 -22]
 [-31 -24 -34 -20]]
[[774 828 350 846]
 [496 846 390 608]
 [752 756 611 384]]
[[0.41860465 0.39130435 0.28571429 0.38297872]
 [0.51612903 0.38297872 0.43333333 0.42105263]
 [0.34042553 0.42857143 0.27659574 0.375     ]]


In [ ]:
# another way of doing these operations
print(np.add(c,d))
print(np.subtract(c,d))
print(np.multiply(c,d))
print(np.divide(c,d))

[[61 64 45 65]
 [47 65 43 54]
 [63 60 60 44]]
[[-25 -28 -25 -29]
 [-15 -29 -17 -22]
 [-31 -24 -34 -20]]
[[774 828 350 846]
 [496 846 390 608]
 [752 756 611 384]]
[[0.41860465 0.39130435 0.28571429 0.38297872]
 [0.51612903 0.38297872 0.43333333 0.42105263]
 [0.34042553 0.42857143 0.27659574 0.375     ]]


#Array Manipulation

In [ ]:
e = np.random.randint(10,60,(4,6))
print(e)
print(e.shape)
trans1 = np.transpose(e)
print(trans1)
print(trans1.shape)

[[23 29 41 41 49 46]
 [15 25 25 23 32 30]
 [54 11 50 28 36 14]
 [16 44 55 32 49 32]]
(4, 6)
[[23 15 54 16]
 [29 25 11 44]
 [41 25 50 55]
 [41 23 28 32]
 [49 32 36 49]
 [46 30 14 32]]
(6, 4)


In [ ]:
# another way of doing transpose
trans2 = e.T
print(trans2)
print(trans2.shape)

[[23 15 54 16]
 [29 25 11 44]
 [41 25 50 55]
 [41 23 28 32]
 [49 32 36 49]
 [46 30 14 32]]
(6, 4)


In [ ]:
# array reshaping
f = np.random.randint(10,100,(4,6))
print(f)
print(f.shape)

[[88 87 50 53 34 46]
 [72 75 80 65 15 42]
 [99 60 92 54 38 46]
 [44 73 36 28 43 84]]
(4, 6)


In [ ]:
g = f.reshape(2,12)
print(g)
print(g.shape)

[[88 87 50 53 34 46 72 75 80 65 15 42]
 [99 60 92 54 38 46 44 73 36 28 43 84]]
(2, 12)


In [6]:
a = np.array([[1, 2], [3, 4]])
print(a.flatten())   # Convert to 1D

[1 2 3 4]


#Boolean Indexing (Condition-Based)

In [7]:
a = np.array([10, 20, 30, 40])
print(a[a > 20])  # [30 40]

[30 40]


# Broadcasting (Smart size matching)

In [8]:
a = np.array([1, 2, 3])
b = 2

print(a + b)  # [3 4 5] – b is added to all elements

[3 4 5]


#Joining and Splitting Arrays

In [9]:
# Joining
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))

[1 2 3 4]


In [11]:
# Splitting
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 3)) # 3 arrays: [1 2], [3 4], [5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]


#NumPy with Missing or Infinite Values



In [12]:
a = np.array([1, 2, np.nan, 4, np.inf])
print(np.isnan(a))  # Check for NaN
print(np.isinf(a))  # Check for Infinity

[False False  True False False]
[False False False False  True]


#Copy vs View

In [13]:
a = np.array([1, 2, 3])
b = a.copy()  # Real copy (changes don’t affect a)
c = a.view()  # Just a view (changes affect a)

b[0] = 100
c[1] = 200

print(a)
print(b)
print(c)

[  1 200   3]
[100   2   3]
[  1 200   3]
